FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential curl git lib32stdc++-9-dev \
    libc6-dev-i386 nodejs npm python3-dev python3-pip
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y meson

ADD . /repo
WORKDIR /repo
RUN meson build -Ddiet=false
WORKDIR /repo/build
RUN ninja
